### ISSUE TITLE
Users can play a full round of posele

### ISSUE THREAD

**Issue by tymonaghan** [team-posele/posele-app#14]
- [x] user can log in to existing account (#4 )
- [x] see instructions and warning (#5 )
- [x] display pose to user (#12 ) 
- [x] open camera and auto-snap after timer (#11 )
- [ ] give match/fail result (#13 )
